config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :renters do
    resources :reviews
  end
  
  # get '/signin', to: 'devise/sessions#new'

  get 'pages/about'

  get 'pages/contact'

  root 'renters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/renter.rb
class Renter < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :reviews, dependent: :destroy
  validates :first_name, :last_name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :renter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  before_action :set_renter, only: [:show, :edit, :update, :destroy]

  # GET /renters
  # GET /renters.json
  def index
    if user_signed_in?
    #Commented out and replaced by below for search
    # @renters = Renter.all
    #SEARCH!
    @renters = if params[:term]
      Renter.where('first_name LIKE ? OR last_name LIKE ? OR aka LIKE ? OR email LIKE ? OR phone_number LIKE ? OR mobile_phone LIKE ?', "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
      else
        Renter.all
    #END SEARCH
      end

    else redirect_to '/users/sign_in'
    end
  end

  # GET /renters/1
  # GET /renters/1.json
  def show
    @renter = Renter.find(params[:id])
    @reviews = Review.where(renter_id: @renter.id)
    
  end

  # GET /renters/new
  def new
    @renter = Renter.new
  end

  # GET /renters/1/edit
  def edit
  end

  # POST /renters
  # POST /renters.json
  def create
    @renter = Renter.new(renter_params)

    respond_to do |format|
      if @renter.save
        format.html { redirect_to @renter, notice: 'Renter was successfully created.' }
        format.json { render :show, status: :created, location: @renter }
      else
        format.html { render :new }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renters/1
  # PATCH/PUT /renters/1.json
  def update
    respond_to do |format|
      if @renter.update(renter_params)
        format.html { redirect_to @renter, notice: 'Renter was successfully updated.' }
        format.json { render :show, status: :ok, location: @renter }
      else
        format.html { render :edit }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter.destroy
    respond_to do |format|
      format.html { redirect_to renters_url, notice: 'Renter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renter
      @renter = Renter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def renter_params
      params.require(:renter).permit(:first_name, 
                                    :last_name, 
                                    :aka, 
                                    :email, 
                                    :street_address, 
                                    :city, 
                                    :state, 
                                    :zip, 
                                    :phone_number, 
                                    :mobile_phone, 
                                    :vrbo_url, 
                                    :airbnb_url, 
                                    :facebook_url, 
                                    :linkedin_url, 
                                    :misc, 
                                    :image,
                                    :user_id,
                                    :term)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_renter
  before_action :authenticate_user!

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.renter_id = @renter.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to renter_path(@renter), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to renter_path(@renter), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to renter_path(@renter), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Added per tut -tp
    def set_renter
      @renter = Renter.find(params[:renter_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating_overall, 
                                    :rating_damage, 
                                    :rating_payment, 
                                    :rating_communication, 
                                    :rating_checkinout, 
                                    :people_number, 
                                    :comment, 
                                    :property_name, 
                                    :property_address, 
                                    :property_unit, 
                                    :property_city, 
                                    :property_state, 
                                    :property_zip,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_bootstrap.html.erb
<%# Bootstrap CDN %>
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"> -->
<%# JQuery for Bootstrap %>
<%#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>%>
<%# Bootstrap Javascript Bundle (Includes Popper)%>
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.bundle.min.js"></script> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">&copy 2018 Rabun Rental Community</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<%#Bootstrap Navbar%>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to image_tag("rabun_logo_web_wht_sml.png", alt: "logo"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to  "About", pages_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Contact", pages_contact_path, class: "nav-link" %>
        </li>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> %>
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search Renters" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
      <%#SEARCH FORM%>
      <%= form_tag(renters_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search Renters", autofocus: true %>
      <%= submit_tag 'GO', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
      <%#END SEARCH FORM%>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="nav-item" id="username-nav">
          <%= link_to edit_user_registration_path do %>
          Hello, <br><%=current_user.first_name.capitalize%> <%=current_user.last_name.capitalize%>!
              <% end %>
          </li>
          <li class="nav-item hover-not">
              <%# Replaced with font-awesome icon %>
              <%#= link_to  "Edit Profile", edit_user_registration_path, class: "nav-link" %>
              <%= link_to fa_icon("user", class: "fa fa-user"), edit_user_registration_path %>
            </li> 
            <li class="nav-item">
              <%# Replaced with font-awesome icon %>
              <%#= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <%= link_to fa_icon("sign-out", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete %>
          </li>
          <% else %>

          <li class="nav-item">
            <%= link_to  "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to  "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
            
      </ul>
    </div>
  </nav>
  <%#/Bootstrap Navbar%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RabunApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/bootstrap' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <%#Required for Devise Gem to send notifications to users, replaced later by new code%>
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="rabun-table-div">
  <h1>About Rabun Rental Community</h1>
  <p>Read more about <%= link_to  "Lake Rabun", "https://en.wikipedia.org/wiki/Lake_Rabun" %></p>
</div>

app/views/pages/contact.html.erb
<div class="rabun-table-div">
  <h1>Contact Us</h1>
  <p><a href="mailto: info@rabunrentalcommunity.com">Click here to email us!</a></p>
</div>

app/views/renters/edit.html.erb
<div class="rabun-table-div">
  <h1>Editing Renter</h1>

  <%= render 'form', renter: @renter %>

  <%= link_to 'Show', @renter, class: "btn btn-link" %> |
  <%= link_to 'Back', renters_path, class: "btn btn-link" %>
</div>

app/views/renters/index.html.erb
<!-- <h1>Renters</h1> -->
<!-- <h3 class="float-right">Hello, <%=current_user.first_name.capitalize%> <%=current_user.last_name.capitalize%>!</h3><br> -->

<!-- <%= link_to '+ New Renter', new_renter_path, class: "btn btn-info" %> -->
<div class="rabun-table-div">
  <h2>Renters</h2>
  <p>All known renters in our system are shown below.  Search any field by typing in the search box above.</p>
  <div id="renter-table-div">
  <div class="row">
    <h6 class="col-12">Click on any renter to see their profile and reviews.</h6>
  </div>
  <div class="row justify-content-end">
    <%= link_to '+ Add a Renter', new_renter_path, id: "new-renter-button", class: "btn btn-primary" %><br>
  </div>
  <br>
  <table class="table table-hover">
    <thead class="thead">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Aka</th>
        <th>Email</th>
        <th>Phone number</th>
        <th>Mobile phone</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @renters.order(:last_name).each do |renter| %>
        <tr data-link="<%= renter_path(renter) %>">
          <td><%= link_to renter.first_name, renter %></td>
          <td><%= link_to renter.last_name, renter  %></td>
          <td><%= link_to renter.aka, renter  %></td>
          <td><%= link_to renter.email, renter  %></td>
          <td><%= link_to renter.phone_number, renter  %></td>
          <td><%= link_to renter.mobile_phone, renter  %></td>
          <!--<td><%= link_to 'Show', renter, class: "btn btn-primary" %></td>-->
          <!-- <td><%#= link_to 'Edit', edit_renter_path(renter), class: "btn btn-link" %></td> -->
          <!-- <td><%#= link_to 'Destroy', renter, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

<br>

app/views/renters/new.html.erb
<div class="rabun-table-div">

  <h1>New Renter</h1>
  <p>Enter as much info as you know about the renter, especially any that might help identify the person and differentiate them from similar renters.  All fields except First and Last Name are optional.</p>
  <hr>

  <%= render 'form', renter: @renter %>

  <%= link_to 'Back', renters_path, class: "btn btn-link" %>
</div>

app/views/renters/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="rabun-table-div">
<div class="row">
    <%= link_to '<-Back to Renters', renters_path, class: "btn btn-link" %>
</div>
<div class="row justify-content-center">
    <h1 class="renter-big-name"><%= "#{@renter.first_name} #{@renter.last_name}"%></h1>
</div>  
<div class="row">
  <div class="col-md-3 renter-column">
      <h4><span style="text-decoration:underline;">Renter Profile:</span></h4>
      <hr>
      <h5>Name/Identity</h5>
      <p>
          <strong>First name:</strong><br>
          <%= @renter.first_name %>
        </p>
        
        <p>
          <strong>Last name:</strong><br>
          <%= @renter.last_name %>
        </p>
        
        <p>
          <strong>Aka:</strong><br>
          <%= @renter.aka %>
        </p>
        
        <h5>Contact Info</h5>
        <p>
          <strong>Email:</strong><br>
          <%= @renter.email %>
        </p>

        <p>
          <strong>Phone number:</strong><br>
          <%= @renter.phone_number %>
        </p>
          
        <p>
          <strong>Mobile phone:</strong><br>
          <%= @renter.mobile_phone %>
        </p>
        
        <h5>Physical Address</h5>
        <p>
          <strong>Street address:</strong><br>
          <%= @renter.street_address %>
        </p>
        
        <p>
          <strong>City:</strong><br>
          <%= @renter.city %>
        </p>
        
        <p>
          <strong>State:</strong><br>
          <%= @renter.state %>
        </p>
        
        <p>
          <strong>Zip:</strong><br>
          <%= @renter.zip %>
        </p>
        
        <h5>Social/Online</h5>
        
        <p>
          <strong>Vrbo url:</strong><br>
          <%= @renter.vrbo_url %>
        </p>
        
        <p>
          <strong>Airbnb url:</strong><br>
          <%= @renter.airbnb_url %>
        </p>
        
        <p>
          <strong>Facebook url:</strong><br>
          <%= @renter.facebook_url %>
        </p>
        
        <p>
          <strong>Linkedin url:</strong><br>
          <%= @renter.linkedin_url %>
        </p>
        <h5>Other</h5>
        <p>
          <strong>Misc:</strong>
          <%= @renter.misc %>
        </p>
        <% if Renter.find(params[:id]).user_id == current_user.id %>
          <%= link_to 'Edit Renter', edit_renter_path(@renter), class: "btn btn-warning", id: "renter-panel-edit-btn" %>
          <%= link_to 'Delete Renter', @renter, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", id: "renter-panel-delete-btn" %>
        <% end %>

        
  </div>
  <div class="col-md-9 reviews-column">
      <div class="row justify-content-center">
      <h4><span style="text-decoration:underline">Reviews on this renter:</span></h4>
      </div>
      <hr>
      <%= link_to  "+ Add a New Review", new_renter_review_path(@renter), class: "btn btn-primary"%>
      <% if @reviews.blank? %>
        <h3>No reviews yet.</h3>
      <% else %>
        <% @reviews.order('created_at DESC').each do |review| %>
          <div class="review-bubble">
            <h6><%= "Reviewed by #{review.user.first_name.capitalize} #{review.user.last_name.capitalize} on #{review.created_at.strftime("%-m/%-d/%y")}:" %></h6>
            <p><%= "Overall Rating: #{review.rating_overall}" %></p>
            <p><%= review.comment %></p>
            <!-- <p><em><%= "by #{review.user.first_name.capitalize} #{review.user.last_name.capitalize}." %></em></p> -->
            <!-- <p><%= "Created on #{review.created_at.strftime("%-m/%-d/%y")}" %></p> -->
            <% if review.user_id == current_user.id %>
              <%= link_to 'Edit Review', edit_renter_review_path(@renter, review), class: "btn btn-warning" %>
              <%= link_to 'Delete Review', renter_review_path(@renter, review), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>





<%#= link_to 'Edit', edit_renter_path(@renter), class: "btn btn-link" %>

</div>

app/views/reviews/edit.html.erb
<div class="rabun-table-div">

  <h1>Editing Review</h1>

  <%= render 'form', review: @review %>

  <%#Links below are stubs to be filled later, added the renter path one%>
  <%#= link_to 'Show', '#' %> |
  <%= link_to 'Back', renter_path(@renter) %>

</div>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating overall</th>
      <th>Rating damage</th>
      <th>Rating payment</th>
      <th>Rating communication</th>
      <th>Rating checkinout</th>
      <th>People number</th>
      <th>Comment</th>
      <th>Property name</th>
      <th>Property address</th>
      <th>Property unit</th>
      <th>Property city</th>
      <th>Property state</th>
      <th>Property zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating_overall %></td>
        <td><%= review.rating_damage %></td>
        <td><%= review.rating_payment %></td>
        <td><%= review.rating_communication %></td>
        <td><%= review.rating_checkinout %></td>
        <td><%= review.people_number %></td>
        <td><%= review.comment %></td>
        <td><%= review.property_name %></td>
        <td><%= review.property_address %></td>
        <td><%= review.property_unit %></td>
        <td><%= review.property_city %></td>
        <td><%= review.property_state %></td>
        <td><%= review.property_zip %></td>
        <td><%#= link_to 'Show', # %></td>
        <td><%#= link_to 'Edit', edit_review_path(review) %></td>
        <td><%#= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_renter_review_path %>

app/views/reviews/new.html.erb
<div class="rabun-table-div">

  <h1>New Review</h1>
  <p>Enter any information you'd like to share that might be helpful to others renting to this person.</p>
  <hr>

<%= render 'form', review: @review %>

<%#Link below is stubb to be filled later%>
<%= link_to 'Back to Renters', renter_path(@renter) %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating overall:</strong>
  <%= @review.rating_overall %>
</p>

<p>
  <strong>Rating damage:</strong>
  <%= @review.rating_damage %>
</p>

<p>
  <strong>Rating payment:</strong>
  <%= @review.rating_payment %>
</p>

<p>
  <strong>Rating communication:</strong>
  <%= @review.rating_communication %>
</p>

<p>
  <strong>Rating checkinout:</strong>
  <%= @review.rating_checkinout %>
</p>

<p>
  <strong>People number:</strong>
  <%= @review.people_number %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Property name:</strong>
  <%= @review.property_name %>
</p>

<p>
  <strong>Property address:</strong>
  <%= @review.property_address %>
</p>

<p>
  <strong>Property unit:</strong>
  <%= @review.property_unit %>
</p>

<p>
  <strong>Property city:</strong>
  <%= @review.property_city %>
</p>

<p>
  <strong>Property state:</strong>
  <%= @review.property_state %>
</p>

<p>
  <strong>Property zip:</strong>
  <%= @review.property_zip %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>